### ISSUE TITLE
Формы забыли пароль 20min

### ISSUE THREAD

**Issue by pioh** [lessonhome/lessonhome#126]
Необходимо сделать страницу с формой восстановления пароля, там должно быть поле ввода логина(телефон или емэил), сверстать страницу после успешного отправки запроса на восстановление (с текстом например письмо со ссылкой на восстановление отправлено вам на электронный адресс), сверстать страницу на которую переход в случае отправки кода на телефон( с текстом введите код в поле ввода для изменения пароля и кнопкой отправить код повторно). Сверстать страницу на которую он попадает, если успешно ввел код или если нажал на ссылку, на этой странице два поля введите новый пароль и введите новый пароль еще раз.

**Comment by pioh** [comment]
Нету страницы с сообщением мы отправили вам ссылку с востановлением пароля на емэил когда он емэил вводит.

**Comment by blown1** [comment]
Если ввел имейл, то сообщение должно быть, "мы выслали вам на email ссылку и код для восстановления пароля...."

**Comment by blown1** [comment]
Новую страницу создавать не надо
