### ISSUE TITLE
Оформление заявки

### ISSUE THREAD

**Issue by blown1** [lessonhome/lessonhome#141]
Убрать кнопку "Удалить все". Сделать возможность удаления прикрепленного репетитора через крестик на самой фото. Сделать возможность восстановления удаленного репетитора.
![_ _1](https://cloud.githubusercontent.com/assets/8149119/8329322/30490db0-1a81-11e5-8e16-733b3c357ad2.jpg)

**Comment by mmming** [comment]
5min
