### ISSUE TITLE
Оформление заявки - место занятий

### ISSUE THREAD

**Issue by blown1** [lessonhome/lessonhome#142]
Сделать возможность указания района или метро, при выборе занятий у себя или репетитора. Если выбирает оба варианта, то просто дополняет уже сформированные районы или метро.
![_ _2](https://cloud.githubusercontent.com/assets/8149119/8329391/d39ca40e-1a81-11e5-8452-c023921e1802.jpg)

**Comment by mmming** [comment]
15min (оно сделано, нужно только чуть поправить)
