### ISSUE TITLE
Переверстать фильтр поиска заявок

### ISSUE THREAD

**Issue by mmming** [lessonhome/lessonhome#171]
![_ _1](https://cloud.githubusercontent.com/assets/9805607/8618294/4b9d3adc-2715-11e5-853b-8a16ac665a7b.jpg)
![_ _2](https://cloud.githubusercontent.com/assets/9805607/8618293/4b8e879e-2715-11e5-9900-961d4d2b7b1e.jpg)

**Comment by blown1** [comment]
Серый в понедельник крайний срок!
