### ISSUE TITLE
Корректность ввода данных в input

### ISSUE THREAD

**Issue by seregamurzenok** [lessonhome/lessonhome#18]
реализовать функциональность проверки корректности ввода данных в input.
Виды обработки логики:
1. Поля ввода времени (например на странице http://127.0.0.1:8081/third_step расширенный фильтр - расписание)  в которые можно ввести только цифры, их ограниченное количество - 2 и значение в диапозоне от 0 до 24.
2. В слайдерах (ползунках) ввод значений ограничивается мин и макс числом, соответственно. При вводе больше или меньше установленных мин и макс значений, в поле автоматически переключается значение на крайние. Там где одно поле ввода макс и мин по такой же логике. Пока значения можешь ставить тестовые, для проверки, потом дам реальные.
3. В поле ввода телефона сделать паттерн - +7 (_ _ _) _ _ _-_ _-_ _
4. В поле ввода email, проверять на правильность ввода почты - _____@____.__
5. В полях ввода имя фамилии, короче там где должны быть строки проверять на корректность, выставить ограничение по вводу символов, пока тоже тестовое.
6. Поля ввода логина и пароля проверка на минимальное количество символов - не меньше 4 для логина и 6 для пароля.

**Comment by LinkFly** [comment]
Пункт 2 желательно вынести в отдельную задачу, так как технически он имеет мало общего с остальными пунктами

**Comment by blown1** [comment]
ок, второй пункт вынесу как новую.

**Comment by blown1** [comment]
Коррекция пункта 6.
6. Поля ввода логина и пароля комбинированный функционал как с полем телефон и email

**Comment by LinkFly** [comment]
п.1 (проверка ввода кол-ва часов): сделано в состоянии /home/sergey/lessonhome/www/lessonhome/states/calendar.coffee, можно посмотреть на странице http://127.0.0.1:8081/third_step
п.3 (проверка ввода телефона): сделано в состоянии /home/sergey/lessonhome/www/lessonhome/states/main/fast_bid/first_step.coffee, можно посмотреть на странице http://127.0.0.1:8081/fast_bid/first_step
п.4 (проверка ввода email): ==.== (там же)
п.5 (проверка ввода корректного имени): ==.== (там же)
п.6 (проверка логина (email или телефон) и пароля): сделано в состоянии /home/sergey/lessonhome/www/lessonhome/states/main/main_tutor.coffee для страницы http://127.0.0.1:8081/main_tutor

P.S. Необходимо будет сделать следующий рефакторинг: 
 - инкапсулировать использование одних и тех же ограничений на ввод (сделать несколько "валидаторов" общего пользования)
 - сократить API - сделать использование валидаторов, только через св-во validators (в состоянии)
 - сделать чтобы можно было задавать в validators и массив и объект

**Comment by LinkFly** [comment]
Строка об ошибке на данный момент выводится в консоль

**Comment by blown1** [comment]
Замечания по пунктам:
Общее:
 При вводе некорректного значения, а потом удалении значения, поле подсвечивается - должно принимать первоначальное состояние.

1. В поле времени вводятся символы, должны быть только цифры, а также нет ограничений по вводу цифр(сделать паттерн _ _:_ _ пример: 16:30).

3. Сделать паттерн видимым на странице - +7(111)111–11–11 , чтобы пользователь видел шаблон. Вместо "1" сделать "_". А также при вводе данных курсор перескакивал в нужное поле ввода.

5. Ввод имени и т.д. не должен принимать цифры. 

6. Проверка на email работает, на телефон надо поставить сделать возможным ввод: +7(номер 10 знаков) либо 8(номер 10 знаков), либо (номер 10 знаков).

**Comment by LinkFly** [comment]
п.1 на странице http://127.0.0.1:8081/fourth_step для календаря где ввод времени - теперь разрешён только ввод цифр и ':' и убрано min/max ограничение, так как значение в поле уже не является кол-вом часов (состояние .../calendar.coffee)

п.2 на странице http://127.0.0.1:8081/tutor/profile/second_step поставлен placeholder +7(xxx)xxx–xx–xx  (состояние .../states/contacts_tutor.coffee)

п.3 на странице http://127.0.0.1:8081/tutor/profile/first_step запрещён ввод отличных от букв символов для имени, фамилии, отчества (состояние .../states/general_data.coffee)

------------------------------
п.4 и автоматический перевод курсора на следующую группу цифр, при вводе времени (п.1) и телефона (п.2) будет сделан позже.

**Comment by LinkFly** [comment]
п.4 сделан - ввод номера теперь может производится в 4-ёх вариантах
