### ISSUE TITLE
Создать вторую версию страницы регистрация репетиторов

### ISSUE THREAD

**Issue by blown1** [lessonhome/lessonhome#182]
Дизайн Саша.

**Comment by blown1** [comment]
![screenshot-lessonhome ru 2015-07-22 18-16-28](https://cloud.githubusercontent.com/assets/8149119/8829322/ab281b74-309e-11e5-8d10-9ceb13d77c64.png)

**Comment by mmming** [comment]
https://drive.google.com/open?id=0B-ps_IANt_K9WWMzSERuYV9vRHc

![3](https://cloud.githubusercontent.com/assets/9805607/8830315/423ed250-30a4-11e5-874f-1c1ec20a3a5e.png)

**Comment by mmming** [comment]
https://drive.google.com/open?id=0B-ps_IANt_K9WWMzSERuYV9vRHc
![3](https://cloud.githubusercontent.com/assets/9805607/8830412/bfe5001c-30a4-11e5-934d-b87ff0a9f27f.png)

**Comment by blown1** [comment]
done
