### ISSUE TITLE
Сверстать версии главной страницы

### ISSUE THREAD

**Issue by blown1** [lessonhome/lessonhome#183]
Добавь макеты.

**Comment by mmming** [comment]
https://drive.google.com/file/d/0B-ps_IANt_K9czV3S0NSNGR0Xzg/view

![01](https://cloud.githubusercontent.com/assets/9805607/8829657/7ddaacfc-30a0-11e5-8368-65e1deb70fdb.png)
![02](https://cloud.githubusercontent.com/assets/9805607/8829656/7dd35272-30a0-11e5-839d-d408f41aaba5.png)
