### ISSUE TITLE
Курсоры в формах

### ISSUE THREAD

**Issue by pioh** [lessonhome/lessonhome#2]
На всех страницах привести курсоры в формах к нормальному виду (отступ, высота, соответствие размеру шрифта).
![form_lesson](https://cloud.githubusercontent.com/assets/6367733/6184065/3a6aa896-b36e-11e4-8999-ef8331dd818f.png)
![form_google](https://cloud.githubusercontent.com/assets/6367733/6184066/3d6c1a0c-b36e-11e4-987b-82edc19ec2d1.png)

**Comment by blown1** [comment]
Задача готова
