### ISSUE TITLE
Клик по иконкам

### ISSUE THREAD

**Issue by blown1** [lessonhome/lessonhome#36]
В разделе быстрой заявки(http://127.0.0.1:8081/fast_bid/first_step) и предрегистрации репетитора(http://127.0.0.1:8081/tutor/profile/first_step), сделать возможным переход по страницам через клик. Логика перехода следующая: если иконка активна(пользователь уже был на этой странице), то он может на нее перейти.
![2015-02-25 15 03 31](https://cloud.githubusercontent.com/assets/8149119/6370325/2bfcab56-bd00-11e4-96e9-1e7b8c69bcbe.png)

**Comment by seregamurzenok** [comment]
Сделано без сохранения. При клике на предыдущие пункты, текущие пункты не сохраняются нигде
