### ISSUE TITLE
Привести кнопки к одному виду с учётом эффекта нажатия

### ISSUE THREAD

**Issue by seregamurzenok** [lessonhome/lessonhome#39]

**Comment by blown1** [comment]
Серый, я сделал button, local_button, toggle_button, link_button. У тебя я заметил в формах есть еще кнопка result_button, я ее не трогал, возможно есть еще где нибудь...посмотри

**Comment by blown1** [comment]
Серый, эта задача у нас в приоритете, берись за нее, после того как закончишь то что начал.
