### ISSUE TITLE
Реализовать стиль инпута при ошибки ввода данных

### ISSUE THREAD

**Issue by blown1** [lessonhome/lessonhome#54]
Взять файл на диске 000_LH_GUI.psd, в макете есть стиль инпута и текста ошибки, реализовать как в макете.

**Comment by blown1** [comment]
Пока текст не трогаешь, только стиль рамки

**Comment by LinkFly** [comment]
По хорошему надо переделать с использованием добавления/удаления класса, но пока не ясно как это сделать - другие стили перебивают стили добавляемые классом .bad-input, спецификатор !important не помог

**Comment by mmming** [comment]
●　при фокусе инпута сбоку всплывает подсказка
●　при сбросе фокуса (при переходе на другой инпут например)  рамка инпута меняет цвет и внизу добавляется текст ошибки (сдвигая другие инпуты)
●　при возвращении фокуса в инпут ошибкой - он переходит в обычное состояние фокуса

**Comment by LinkFly** [comment]
Сделан пробный макет блока с всплывающей подсказкой, размещён здесь: http://codepen.io/LinkFly/pen/XJxyox/?editors=110
Пока буду реализовывать алгоритм всплытия и выборки связанной с элементом подсказки...

**Comment by blown1** [comment]
Реализовано
