### ISSUE TITLE
Скрол в выпадающем списке

### ISSUE THREAD

**Issue by blown1** [lessonhome/lessonhome#66]
Реализовать пользовательский скрол со своими стилями в drop_down_list. Прилагаю скрин, более подробно в ГУИ.
![2015-03-13 17 11 04](https://cloud.githubusercontent.com/assets/8149119/6662195/81be5daa-cbc9-11e4-86a1-e72d905e938c.png)

**Comment by LinkFly** [comment]
Пока сделал рабочую модель на codepen.io:
http://codepen.io/LinkFly/pen/Kwroya/

**Comment by blown1** [comment]
Убрать выделение со скрола и самого бокса.

**Comment by LinkFly** [comment]
Появление выделения замечено (бокса с текстом в input'e) пока только при выходе за пределы при перетаскивании скролла.

**Comment by LinkFly** [comment]
Стрелочки показаны - но их надо будет сделать меньше, в соотв. с макетом

**Comment by LinkFly** [comment]
А также надо будет решить следующую проблему - при управлении скроллом исчезает подсветка input'a так как он теряет фокус

**Comment by LinkFly** [comment]
P.S. Залил только пока в свою ветку LinkFly
