### ISSUE TITLE
Drop Down List with ability to enter 

### ISSUE THREAD

**Issue by seregamurzenok** [lessonhome/lessonhome#8]
- написать функциональность выпадения нужных элементов по мере ввода
- написать функциональность клика по значению списка
- написать функциональность перемещения по выпадающему списку стрелочками вверх/вниз
- написать функциональность фокусирования на input

**Comment by LinkFly** [comment]
Внимание переключение на элемент в списке по нажатию клавиш up, down на клавиатуре реализуется с использованием setTimeout (без этого не корректно обрабатывается переключение при достижении верхнего/нижнего значений). Нужно разобраться разобраться в причинах и сделать корректно.

**Comment by LinkFly** [comment]
Функционал доделан, необходимо сделать корректную вёрстку, чтобы список с предлагаемыми значениями размещался строго под input'ом

**Comment by blown1** [comment]
1. При вводе символов не выпадают совпадающие слова.
2. При фокусе и вводе символов, а потом их удалении выпадает список, как будто был клик по треугольнику, этого не должно быть, список выпадает и скрывается только при  нажатии на треугольник.
![2015-03-13 15 45 54](https://cloud.githubusercontent.com/assets/8149119/6638532/2492fccc-c998-11e4-92aa-3d2669b3c510.png)

**Comment by blown1** [comment]
При вводе символов и выпадении из списка слов начало которых совпадает с введенными символами, совпадение символов в выпадающем списке должно быть стилистически подкрашено как в файле гуи.

**Comment by blown1** [comment]
Скидываю скрин из файла Gui, реализовать в таком стиле
![2015-03-13 17 11 04](https://cloud.githubusercontent.com/assets/8149119/6639865/3352a846-c9a4-11e4-8b47-eb64d12fe37d.png)

**Comment by LinkFly** [comment]
Создание собственного скролла - большой кусок работы, это необходимо вынести в отдельную задачу. Кроме того, чтобы добавить такой функционал к выпадающему списку необходимо провести рефакторинг текущего drop_down_list и подумать насчёт вынесения выпадающего списка в отдельный компонент. 
Пока сделаю:
- padding'и
- максимальную высоту 
- появление дефолтного скролла
- позиционирование под input'ом

**Comment by blown1** [comment]
1. Если список раскрыт и произошло нажатие вне его области (потеря фокуса), то список должен сворачиваться а сам box принимать обычное состояние как при потере фокуса
2. Сейчас при выборе из списка какого нибудь значения, повторно вызвать выпадение списка не получается, пофиксить.
Насчет скрола составлю новую задачу

**Comment by LinkFly** [comment]
Выявилось две проблемы: 
 - если одно значение - то выпадающий список всё-таки не появляется
 - если в значении используются круглы скобки то происходит ошибка (ясно из-за чего, пофиксить достаточно быстро)

**Comment by blown1** [comment]
Оптимизировать модуль и стили качающиеся выпадающего списка

**Comment by blown1** [comment]
Небольшие поправки в логике:
1. При фокусе список всегда раскрыт.
2. Показывается первые 5 значений(сделать так чтобы через свойство можно было изменять количество показываемых предметов). Остальные можно прокрутить в скроле.
3. Значения показываются в алфавитном порядке(пока так, потом надо будет сделать логику показа по популярности).
4. При показе подходящих предметов, с помощью кнопки tab перемещение вниз по предметам, аналог стрелки вниз, tab+shift, перемещение вверх, аналог стрелки вверх.

**Comment by blown1** [comment]
3. Значения показываются в алфавитном порядке(пока так, потом надо будет сделать логику показа по популярности). - пока не реализовывай.

**Comment by seregamurzenok** [comment]
не работает, если значения цифры 
![2015-03-19 15 50 54](https://cloud.githubusercontent.com/assets/8384452/6730660/ca06d28a-ce4f-11e4-9b78-1b5fa9a16900.png)

**Comment by blown1** [comment]
При  tab между элементами, фокус не спадает.
![2015-03-19 17 34 15](https://cloud.githubusercontent.com/assets/8149119/6732654/4239d3ac-ce5e-11e4-9915-2c936dd2eaa6.png)

**Comment by LinkFly** [comment]
> seregamurzenok
bug влияющий на выборку цифр - пофиксил

**Comment by LinkFly** [comment]
>Небольшие поправки в логике: ...
3 из 5 пунктов сделаны, по 2 оставшимся пунктам:
  5. Автофокус в моей ветке не стоит
  3. Код для сортировки в алфавитном порядке - оставил закомментированным, так как стандартная ф-ия сорт, сортирует некорректно.
